import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import NavLandingAuth from "@/components/nav/NavLandingAuth";
import NavOther from "@/components/nav/NavOther";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" fixed top-0 left-0 w-full z-20 backdrop-blur-sm bg-white/30">
          <NavLandingAuth />
          <NavOther />
        </div>
        <div className="pt-[3rem] min-h-[calc(100vh-3rem)]">
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
